# Generated by Django 2.2.6 on 2019-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='subject',
            field=models.CharField(max_length=50, null=True, verbose_name='Subject Name'),
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
