# Generated by Django 2.2.6 on 2019-11-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0004_deck_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='deck',
            new_name='parentDeck',
        ),
    ]
