# Generated by Django 2.2.6 on 2019-11-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flash', '0005_auto_20191103_0308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='parentDeck',
            new_name='deck',
        ),
    ]
